### ISSUE TITLE
PIA Openelec

### ISSUE THREAD

**Issue by mark142** [metalkettle/MetalKettles-Addon-Repository#8]
Hi.  The xbmc addon for PIA does not  seem to be working correctly.  I have entered my details but when i try to connect to one of the servers in the openelec settings, It fails to connect and says status failure.  It works fine when using on laptop so it seems to be an addon specific issue,

**Comment by xbmcinvisable** [comment]
You may find you need to log in the client area on pia website and create a socks logging details. Use these with this addon

**Comment by mark142** [comment]
please close this issue, turns out it was a typo in my password in openelec.  Im sorry
